data:
  dataset_name: "cifar10"
  batch_size: 32
  num_workers: 4
  size:
  - 224
  - 224
  data_root: data
  valid_ratio: 0.1

# 2. define model (define other backbone)
model:
  model_name: 'efficientnet_v2_l'
  model_args:
    pretrained: true
  augmentation: 'cutmix'

# 3. prepare train tools (optimizer, learning rate scheduler)
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.01
    momentum: 0.95
    weight_decay: 0.0005

lr_scheduler:
  class_path: src.lr_scheduler.CosineLR
  init_args:
    max_epochs: 0
    num_step: 0
    warmup_epoch: 1

# 4. train
seed_everything: 2021
trainer:
  # 4-1. gpu devices
  gpus: null
  accelerator: null
  amp_backend: native

  # 4-2. train setting
  max_epochs: 100

  # 4-3. logger & callbacks
  log_every_n_steps: 50
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor

  # 4-4. precision
  precision: 32